version: "2"

services:
  shop:
    restart: always
    build: ./shop
    hostname: datashop
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "5666:8000"
    container_name: datashop
    command: python manage.py runserver
    networks:
      - datashop-net

  web:
    restart: always
    build: ./web
    hostname: web
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "5667:3000"
    container_name: datashop-web
    command: npm run start
    #tty: true
    networks:
      - datashop-net

  mongo:
    restart: always
    image: mongo
    hostname: datashop-mongo
    container_name: datashop-mongo
    ports:
      - "22007:27017"
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/johnny/DATASHOP/data/mongo:/etc/mongo
    networks:
      - datashop-net

  crawler:
    restart: always
    build: ./crawler
    hostname: datashop-crawler
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /etc/localtime:/etc/localtime
    container_name: datashop-crawler
    tty: true
    #command: python -c "from stock_list import auto_maintain; auto_maintain();"
    networks:
      - datashop-net

networks:
  datashop-net:
